package ai.rakuten.android.api

/**
 * Central registry of all Rakuten AI Gateway API endpoints and default model names.
 *
 * Two backend providers are supported:
 * - **Anthropic** — text completions via `claude-*` models
 * - **Google Vertex AI** — image generation via `gemini-*` models
 *
 * The base URLs mirror the `BuildConfig` fields generated by the Gradle build and are kept in
 * sync with [ai.rakuten.android.BuildConfig.RAKUTEN_TEXT_BASE_URL] /
 * [ai.rakuten.android.BuildConfig.RAKUTEN_IMAGE_BASE_URL].
 */
object RakutenApiEndpoints {

    // ── Text (Anthropic) ──────────────────────────────────────────────────────

    /** Base URL for Anthropic-compatible text completions. */
    const val TEXT_BASE_URL = "https://api.ai.public.rakuten-it.com/anthropic/"

    /** Anthropic API version header value. */
    const val TEXT_API_VERSION = "2023-06-01"

    /** Chat completions path, appended to [TEXT_BASE_URL]. */
    const val TEXT_MESSAGES_PATH = "v1/messages"

    /** Default Claude wire model name. */
    const val DEFAULT_TEXT_MODEL = "claude-sonnet-4-6"

    // ── Image (Google Vertex AI) ──────────────────────────────────────────────

    /** Base URL for Google Vertex AI image generation. */
    const val IMAGE_BASE_URL = "https://api.ai.public.rakuten-it.com/google-vertexai/v1/"

    /** Default Gemini image model. */
    const val DEFAULT_IMAGE_MODEL = "gemini-3.1-flash-image-preview"

    /**
     * Builds the full image generation endpoint URL for the given [model].
     *
     * The Rakuten AI Gateway routes Google Vertex AI calls using the Vertex AI path convention:
     * `publishers/google/models/{model}:generateContent` (not the AI-Studio-style `models/{model}`).
     * This matches what the google-genai Python SDK sends when `vertexai=True`.
     *
     * Example: `https://…/v1/publishers/google/models/gemini-3.1-flash-image-preview:generateContent`
     */
    fun imageGenerateUrl(model: String = DEFAULT_IMAGE_MODEL): String =
        "${IMAGE_BASE_URL}publishers/google/models/$model:generateContent"
}
